version: "3"
services:
    frontend:
        build: .
        image: frontend
        container_name: frontend
        ports:
            - "3000:3000"
        expose:
            - "3000"
        environment:
            API_HOST: ${API_HOST}
        command: npm start
        volumes:
            - "./frontend:/app"
        depends_on:
            - backend
        links:
            - backend

    backend:
        build: .
        image: backend
        container_name: backend
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            RAILS_ENV: development
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST: psg
        command: bundle exec rails s -p '8080' -b '0.0.0.0'
        volumes:
            - "./backend:/app"
        depends_on:
            - db
        links:
            - db

    db:
        image: postgres:latest
        container_name: psg
        ports:
            - "5432:5432"
        expose:
            - "5432"
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_HOST_AUTH_METHOD: trust
